services:
  api:
    build: .
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/painel
      JWT_SECRET: super-secret-change
    ports: ["3000:3000"]
    depends_on: [mongo]
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: [mongo_data:/data/db]
volumes:
  mongo_data:
